export const API_URL ="https://norma.nomoreparties.space/api/"
export const ESCAPE_VALUE = "Escape"
export const BURGER_INGREDIENT_BUN_TYPE = "bun"
export const BURGER_INGREDIENT_MAIN_TYPE = "main"
export const BURGER_INGREDIENT_SAUCE_TYPE = "sauce"