export const GET_BURGER_INGREDIENTS: 'GET_BURGER_INGREDIENTS' = 'GET_BURGER_INGREDIENTS';
export const GET_BURGER_INGREDIENTS_SUCCESS: 'GET_BURGER_INGREDIENTS_SUCCESS' = 'GET_BURGER_INGREDIENTS_SUCCESS';
export const GET_BURGER_INGREDIENTS_FIELED: 'GET_BURGER_INGREDIENTS_FIELD' = 'GET_BURGER_INGREDIENTS_FIELD';
export const SET_CURRENT_BURGER_INGREDIENT: 'SET_CURRENT_BURGER_INGREDIENT' = 'SET_CURRENT_BURGER_INGREDIENT';
export const CLEAR_CURRENT_BURGER_INGREDIENT: 'CLEAR_CURRENT_BURGER_INGREDIENT' = 'CLEAR_CURRENT_BURGER_INGREDIENT';